
server:
  port: 8080

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    password: ""
    url: ""
    username: ""
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: false
    open-in-view: false

